
version: 2.1

jobs:

  deploy:
    docker:
        - image: cimg/base:stable
    steps:
      - run:
          command: return 1
  
  roll_back:
    docker:
        - image: cimg/base:stable
    when: on_fail
    steps:
      - run:
          command: echo sending msg to slack channel

workflows:
  default:
    - deploy
    - roll_back:
        requires: deploy

