
version: 2.1

jobs:

  deploy:
    docker:
        - image: cimg/base:stable
    steps:
      - run:
          command: return 1
      - run:
          when: on_fail
          command: echo sending msg to slack channel
  

workflows:
  default:
    jobs:
     - deploy

