version: 2.1

commands:
  print_pipeline_id:
    description: "prints the pipeline id"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:

  print:
    docker:
        - image: cimg/base:stable
    steps:
      - print_pipeline_id


workflows:
  default:
    jobs:
      - print